/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json
 *
 * The version of the OpenAPI document: 1.6
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize};

/// struct for passing parameters to the method [`get_all_maps_maps_get`]
#[derive(Clone, Debug)]
pub struct GetAllMapsMapsGetParams {
    /// Type of content on the map.
    pub content_type: Option<String>,
    /// Content code on the map.
    pub content_code: Option<String>,
    /// Page number
    pub page: Option<u32>,
    /// Page size
    pub size: Option<u32>,
}

/// struct for passing parameters to the method [`get_map_maps_xy_get`]
#[derive(Clone, Debug)]
pub struct GetMapMapsXyGetParams {
    /// The position x of the map.
    pub x: i32,
    /// The position X of the map.
    pub y: i32,
}

/// struct for typed errors of method [`get_all_maps_maps_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllMapsMapsGetError {
    /// Maps not found.
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_map_maps_xy_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetMapMapsXyGetError {
    /// Map not found.
    Status404(),
    UnknownValue(serde_json::Value),
}

/// Fetch maps details.
pub async fn get_all_maps_maps_get(
    configuration: &configuration::Configuration,
    params: GetAllMapsMapsGetParams,
) -> Result<models::DataPageMapSchema, Error<GetAllMapsMapsGetError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let content_type = params.content_type;
    let content_code = params.content_code;
    let page = params.page;
    let size = params.size;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/maps/", local_var_configuration.base_path);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = content_type {
        local_var_req_builder =
            local_var_req_builder.query(&[("content_type", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = content_code {
        local_var_req_builder =
            local_var_req_builder.query(&[("content_code", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = page {
        local_var_req_builder =
            local_var_req_builder.query(&[("page", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = size {
        local_var_req_builder =
            local_var_req_builder.query(&[("size", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetAllMapsMapsGetError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Retrieve the details of a map.
pub async fn get_map_maps_xy_get(
    configuration: &configuration::Configuration,
    params: GetMapMapsXyGetParams,
) -> Result<models::MapResponseSchema, Error<GetMapMapsXyGetError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let x = params.x;
    let y = params.y;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!(
        "{}/maps/{x}/{y}",
        local_var_configuration.base_path,
        x = x,
        y = y
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetMapMapsXyGetError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}
