//! The version of the OpenAPI document: 1.6
//!
//! Generated by: https://openapi-generator.tech

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoldBankResponseSchema {
    #[serde(rename = "data")]
    pub data: Box<models::GoldSchema>,
}

impl GoldBankResponseSchema {
    pub fn new(data: models::GoldSchema) -> GoldBankResponseSchema {
        GoldBankResponseSchema {
            data: Box::new(data),
        }
    }
}
