//! The version of the OpenAPI document: 1.6
//!
//! Generated by: https://openapi-generator.tech

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoldResponseSchema {
    #[serde(rename = "data")]
    pub data: Box<models::GoldTransactionSchema>,
}

impl GoldResponseSchema {
    pub fn new(data: models::GoldTransactionSchema) -> GoldResponseSchema {
        GoldResponseSchema {
            data: Box::new(data),
        }
    }
}
