//! The version of the OpenAPI document: 1.6
//!
//! Generated by: https://openapi-generator.tech

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoldTransactionSchema {
    /// Cooldown details.
    #[serde(rename = "cooldown")]
    pub cooldown: Box<models::CooldownSchema>,
    /// Bank details.
    #[serde(rename = "bank")]
    pub bank: Box<models::GoldSchema>,
    /// Player details.
    #[serde(rename = "character")]
    pub character: Box<models::CharacterSchema>,
}

impl GoldTransactionSchema {
    pub fn new(
        cooldown: models::CooldownSchema,
        bank: models::GoldSchema,
        character: models::CharacterSchema,
    ) -> GoldTransactionSchema {
        GoldTransactionSchema {
            cooldown: Box::new(cooldown),
            bank: Box::new(bank),
            character: Box::new(character),
        }
    }
}
