//! The version of the OpenAPI document: 1.6
//!
//! Generated by: https://openapi-generator.tech

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecyclingItemsSchema {
    /// Objects received.
    #[serde(rename = "items")]
    pub items: Vec<models::DropSchema>,
}

impl RecyclingItemsSchema {
    pub fn new(items: Vec<models::DropSchema>) -> RecyclingItemsSchema {
        RecyclingItemsSchema { items }
    }
}
