//! The version of the OpenAPI document: 2.1
//!
//! Generated by: https://openapi-generator.tech

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskRewardResponseSchema {
    #[serde(rename = "data")]
    pub data: Box<models::TaskRewardDataSchema>,
}

impl TaskRewardResponseSchema {
    pub fn new(data: models::TaskRewardDataSchema) -> TaskRewardResponseSchema {
        TaskRewardResponseSchema {
            data: Box::new(data),
        }
    }
}
