//! The version of the OpenAPI document: 2.1
//!
//! Generated by: https://openapi-generator.tech

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskRewardSchema {
    /// Item code.
    #[serde(rename = "code")]
    pub code: String,
    /// Item quantity.
    #[serde(rename = "quantity")]
    pub quantity: i32,
}

impl TaskRewardSchema {
    pub fn new(code: String, quantity: i32) -> TaskRewardSchema {
        TaskRewardSchema { code, quantity }
    }
}
