//! The version of the OpenAPI document: 2.1
//!
//! Generated by: https://openapi-generator.tech

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenResponseSchema {
    #[serde(rename = "token")]
    pub token: String,
}

impl TokenResponseSchema {
    pub fn new(token: String) -> TokenResponseSchema {
        TokenResponseSchema { token }
    }
}
