//! A Rust wrapper for [Artifacts](https://artifactsmmo.com/), an API-based sandbox MMO.
//!
//! Generated by [openapi-generator](https://openapi-generator.tech/) based on
//! version 5.0 of the [public OpenAPI spec](https://api.artifactsmmo.com/openapi.json).

#![allow(unused_imports)]
#![allow(clippy::too_many_arguments)]

extern crate reqwest;
extern crate serde;
extern crate serde_json;
extern crate url;

pub mod apis;
pub mod models;
pub mod traits;
